USE sales_analysis_db;


CREATE TABLE customers (
customer_id INT,
customer_name VARCHAR(100),
city VARCHAR(50),
signup_date DATE
);
SELECT * FROM customers;


CREATE TABLE orders (
order_id INT,
customer_id INT,
product_id INT,
quantity INT,
order_date DATE,
payment_method VARCHAR(50)
);
SELECT * FROM orders;

-- Find the total number of orders placed in the orders table.
SELECT COUNT(order_id) AS total_orders
FROM orders;

-- Calculate the total revenue generated from all orders.
SELECT * FROM sales_analysis_db.product;

SELECT SUM(total_revenue) AS company_revenue
FROM 
(
SELECT product_name,SUM(price * quantity) AS total_revenue
FROM Orders AS o
JOIN product AS p
ON o.product_id = p.product_id
GROUP BY product_name
ORDER BY total_revenue DESC
) AS sales;

-- Find the top 5 customers who spent the most money.
SELECT * FROM customers;
SELECT * FROM orders;
SELECT * FROM product;

SELECT customer_name,

CONCAT('₹',FORMAT(SUM(price * quantity),0)) AS total_spent
FROM orders AS o
JOIN customers AS c
ON o.customer_id = c.customer_id
JOIN product AS p
ON o.product_id = p.product_id
GROUP BY customer_name 
ORDER BY SUM(price * quantity) DESC LIMIT 5;

-- Identify the top 5 most sold products by quantity.
SELECT * FROM customers;
SELECT * FROM orders;
SELECT * FROM product;

WITH most_sold_product AS 
(
SELECT product_name,SUM(quantity) AS sold_products
FROM orders AS o
JOIN product AS p
ON o.product_id = p.product_id
GROUP BY product_name
ORDER BY sold_products DESC LIMIT 5
)
SELECT product_name, sold_products
FROM most_sold_product;


-- Calculate the total revenue generated by each product category.
SELECT * FROM customers;
SELECT * FROM orders;
SELECT * FROM product;

WITH product_revenue AS
(
SELECT category,SUM(p.price * o.quantity) AS total_revenue
FROM product AS p
JOIN orders AS o
ON p.product_id = o.product_id
GROUP BY category
ORDER BY total_revenue DESC
)
SELECT category, total_revenue 
FROM product_revenue;

-- Find the monthly sales revenue for the year.
SELECT * FROM customers;
SELECT * FROM orders;
SELECT * FROM product;

SELECT 
DATE_FORMAT(order_date,'%Y-%m') AS month_year,
CONCAT('₹',FORMAT(SUM(price * quantity),0)) AS sales_per_month
FROM orders AS o
JOIN product AS p
ON p.product_id = o.product_id
GROUP BY month_year
ORDER BY sales_per_month DESC;

-- Identify customers who placed more than 10 orders.
SELECT * FROM customers;
SELECT * FROM orders;
SELECT * FROM product;

SELECT customer_name, COUNT(order_id) AS order_quantity
FROM customers AS c
JOIN orders AS o
ON c.customer_id = o.customer_id
GROUP BY customer_name
HAVING COUNT(order_id)>10


-- Find the top 3 cities with the highest total revenue.
SELECT * FROM customers;
SELECT * FROM orders;
SELECT * FROM product;

SELECT city,SUM(price * quantity) AS top_cities
FROM customers AS c
JOIN orders AS o
ON c.customer_id = o.customer_id
JOIN product AS p
ON o.product_id = p.product_id
GROUP BY city
ORDER BY top_cities DESC LIMIT 3;

-- Find customers who have never placed an order.
SELECT * FROM customers;
SELECT * FROM orders;
SELECT * FROM product;

SELECT c.customer_name
FROM customers AS c
LEFT JOIN orders AS o
ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;


-- Rank all products based on total revenue generated using a window function.
SELECT p.product_name,SUM(p.price * o.quantity) AS total_revenue,
RANK() OVER(ORDER BY SUM(p.price * o.quantity) DESC) AS revenue_rank
FROM orders o
JOIN product p
ON o.product_id = p.product_id
GROUP BY p.product_name;

-- Find the second highest revenue generating product.
WITH product_revenue AS (
SELECT p.product_name,SUM(p.price * o.quantity) AS total_revenue
FROM orders AS o
JOIN product AS p
ON o.product_id = p.product_id
GROUP BY p.product_name
)
SELECT product_name, total_revenue
FROM (
SELECT *,
DENSE_RANK() OVER(ORDER BY total_revenue DESC) AS new_rank
FROM product_revenue
) AS ranked_products
WHERE new_rank = 2;

-- Calculate the running total of revenue by order date.
SELECT * FROM customers;
SELECT * FROM orders;
SELECT * FROM product;

SELECT order_date,
SUM(p.price * o.quantity) AS daily_revenue,
SUM(SUM(p.price * o.quantity)) 
OVER (ORDER BY order_date) AS running_revenue
FROM orders AS o
JOIN product AS p
ON o.product_id = p.product_id
GROUP BY order_date
ORDER BY order_date;

-- Find customers whose total spending is above average.
SELECT * FROM customers;
SELECT * FROM orders;
SELECT * FROM product;

WITH customer_total AS
(
SELECT customer_name,SUM(price * quantity) AS total_spending
FROM customers AS c
JOIN orders AS o
ON c.customer_id = o.customer_id
JOIN product AS p
ON o.product_id = p.product_id
GROUP BY customer_name
) 
SELECT customer_name 
FROM customer_total 
WHERE total_spending > (SELECT AVG(total_spending)FROM customer_total)

-- Find the top product in each category using ROW_NUMBER().
SELECT * FROM customers;
SELECT * FROM orders;
SELECT * FROM product;

WITH top_product AS
(
SELECT p.product_name,p.category,p.price,
ROW_NUMBER() OVER(PARTITION BY p.category ORDER BY p.price DESC) AS rank_number
FROM product AS p
)
SELECT product_name, category, price
FROM top_product
WHERE rank_number = 1;